name: "CI Tests"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened] 

jobs:
  test:
    runs-on: ubuntu-18.04
    name: "[${{matrix.otp}}/${{matrix.elixir}}] CI Tests [OTP/Elixir]"
    strategy:
      fail-fast: false
      matrix:
        otp: [21.3, 22.3, 23.3, 24.2]
        elixir: [1.10.4, 1.11.4, 1.12.2, 1.13.4, 1.14.0]
        exclude:
          - otp: 24.2
            elixir: 1.10.4
          - otp: 21.3
            elixir: 1.12.2
          - otp: 21.3
            elixir: 1.13.4
          - otp: 21.3
            elixir: 1.14.0
          - otp: 22.3
            elixir: 1.14.0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mix test
